### ISSUE TITLE
keep source control history intact

### ISSUE THREAD

**Issue by DerAndere1** [hobiseven/Marlin2.0.4.4_6axis_Longer3D#1]
Hi, 

You will find a new branch dev in your repo which is the same as your master branch, but rebased onto https://github.com/tpruvot/Marlin/commit/7efa22ef731ada4867ef6bfc971534d4cbccfbcd which corresponds exactly to the 2.0.4.4_Longer3D tagged release. this keeps your changes but also restores the old version control history of all changes, making it easier to create pull requests etc.

Use the dev branch, not the master branch from now on. Simply fetch from your origin remote (https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D.git) and create a new local branch based on the dev branch.
To do so in vs code, go to the Source control tab.Select the panel that corresponds to the local repository "Marlin2.0.4.4_6axis_Longer3D", click on the button for the currently checked out branch (e.g. master) and select "create new branch from...". call it e.g. "dev" and as reference type in "dev" (without "").

Next time you start, do not start from untracked files but create a fork in github and clone that fork. You can create new branches and during creation of a new branch select any desired commit or tag. 
Using git CLI or github  desktop, you can add additional remotes and fetch from the foreign remote repo. Then you can create a new branch based on a branch / commit / tag of the foreign repo and `git rebase` that branch onto your dev branch or `git cherry-pick` commits from one branch into another one.   

If you like the dev branch, you can rename old master to something else and rename "dev" branch  to "master".

**Comment by hobiseven** [comment]
I did create the local dev branch using Github desktop, and will work in that one.... 
I actually need more training on this, as I started git learning when I made the first hardware port of Marlin on the Longer STM32 last year. Tanguy in now maintaining the repo, and publishes releases on a regular basis for the "plain vanilia" marlin

**Comment by hobiseven** [comment]
Gosh, I tried to update the eprom code commit author to Gabriel, and broke the thing. 
I will debug the code, and once working, will send the whole thing to you....

**Comment by DerAndere1** [comment]
Sorry to hear that you had problems and sorry for yet another non-comiling commit from me. :/ I will fix what I see.

**Comment by DerAndere1** [comment]
Looks like the dev branch in your origin remote (referred to as origin/dev) was never corrupted by your failed git replace. You can verify it in github: https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D/tree/dev . Fetch from origin remote (https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D.git) and checkout the remote branch first before creating a new local branch! To create a new local feature branch "fix_history" based on origin/dev:
```
git fetch origin
git checkout -b fix_history origin/dev
git push origin fix_history
```
At that point fix_history is a copy of dev. You should continue to work on your feature branch (e.g. fix_history) and once it is tested, we can decide how to get the updated code into a master branch. 

Unneeded branches can be later deleted from the github website. If anything goes wrong, I have a local branch which serves only as a backup copy of the current dev branch so I can restore it if required.

**Comment by hobiseven** [comment]
Good Afternoon! I will try this tonight, and also try to improve my GIT knowledge. 
I have now 4 steppers hooked to the board, and I look deeper in planner.cpp, as I may have to tune the machine model there. Let's see what the testing session tonigh will deliver!

**Comment by DerAndere1** [comment]
Ok. dev branch compiles now for the Configuration.h (NON_E_AXES 5). If you can discribe the symptoms of your machine, I might have a clue where the remaining issues stem from. Does G1 work for all axes? Does G28 work for all axes?

**Comment by hobiseven** [comment]
Hi ! Thanks for this. 
I have now 4 steppers connected on the board . I did work in local on dev2.
What goes well : all menus show up correctly with I j k. 
All speed feedrates acceleration and jerks are displayed ok in the menus. 

What is not ok > eeprom. It apparently recognizes well the version but there is then an error message Eeprom index

I sent g1 commands and a g1 x20 f400 gives the same result for y.... and for j! However for some reasons I mooves a lot slower and goes 1/4 of the distance or so!  
This is already super. 

Going in the move axis menu gives a different result x, y > half a turn while I does only 1/8 and j even less. Apparently once we went in the moove axis menu g1 commands do not work anymore. 

I included a change in planner.cpp to get this to happen. More to come but this is already super cool. 

I still need to update dogm lcd to display I and j as so far we only see xyz.

**Comment by DerAndere1** [comment]
I am not sure how to set Microstepping. You can try to change MICROSTEP_MODES in configuration.h:
```
#if NON_E_AXES == 6
  #define MICROSTEP_MODES { 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16 } // [1,2,4,8,16]
#elif NON_E_AXES == 5
  #define MICROSTEP_MODES { 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16 } // [1,2,4,8,16]
#elif NON_E_AXES == 4
  #define MICROSTEP_MODES { 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16 } // [1,2,4,8,16]
#else
  #define MICROSTEP_MODES { 16, 16, 16, 16, 16, 16 } // [1,2,4,8,16]
#endif
```

**Comment by hobiseven** [comment]
Gosh I wanted to go to sleep!!! I try this now!

**Comment by DerAndere1** [comment]
Also #define EEPROM_VERSION "V76" in configuration_store.cpp might have to be incremented to
`#define EEPROM_VERSION "V76"`.  In addition, google how to clear the EEPROM of your board before flashin Marlin. After the flashing, do not forget to send M502 followed by M500 to the machine after flashing Marlin

**Comment by hobiseven** [comment]
Microstepping redefinition did not help. 
Regarding the flash, I disable the internal one, to use the SD card emulation. There is an other probleMm. No big deal. 
J works in G1, but not I... 
Let's see an other day! As I played with the code, I did all that in dev2 branch. 
Cheers!

**Comment by hobiseven** [comment]
You have made quite a few commits yesterday night. Let's see how this works. I will test but late tonight.

**Comment by DerAndere1** [comment]
must have commits: https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D/blob/dev_2/Marlin/src/module/stepper.cpp ; also change configuration_adv.h line [762](https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D/blob/dev_2/Marlin/Configuration_adv.h#L762) and 764. Also have a look at commit  https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D/commit/74bcb683f14735a877282e8b87d7e4e8406066b1 which amongst unrelated stuff changes the `#define HAS_MICROSTEPS` to add code for IJK. 

Finally and most importantly I managed to fix types.h so I can now also compile my fork and help testing in hardware. I will add my changes to the dev branch in the next hours

**Comment by DerAndere1** [comment]
Thanks for your workaround in types.h. It compiles, but it will cause issues when actually used (the extruder parameter is required. I found a solution that compiles and looks reasonable. I created a new branch called "dev_2_rebased" based on dev,  cherry-picked you newest changes and pushed it to your repo, so you will get the combined fixes from both of us. If you do not want to use git for the hardare test you can download the code as zip from the github webinterface (direct download link: https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D/archive/dev_2_rebased.zip ). If you want to do further changes based on that code, instead use git to create a local branch based on reference dev_2_rebased .

**Comment by hobiseven** [comment]
Hehe that is great! Time for quick testing then!

**Comment by hobiseven** [comment]
I will very likely make a local branch. It is so much better so you have also a view on what goes on!

**Comment by hobiseven** [comment]
Ok, so the results are : 


[Video_1629.zip](https://github.com/hobiseven/Marlin2.0.4.4_6axis_Longer3D/files/4313948/Video_1629.zip)

1/ 
G1 X40 Y40 I40 J40 F1000 gets X any Y to do 1 turn anticlockwise, J 1 turn clockwise at the same speed, ang I 1/4 turn anticlockwise.
While my X and Y stepper ( old hacked steppers ) have different wiring ( config.h inverts Y > wires are swapped on that stepper, resulting in the same real direction), I and J are brand new stepper that should turn in the same direction.... There is something strange here. 
I resolution is 4 times smaller than J also.
 
2/ Feedrate calculation :  
G1 X40 F1000 is 4 times faster then G1 X40 Y40 I40 J40 F1000 > In the current feedrate calculation we have 4 movements, and that can be a logical thing for some applications. Not on mine, but this is my issue I and J movements should not really be take in the feedrate calculation. This is a specificity of the foam cutter. The hot wire speed has to be definned on one plae. This is a compromise, I know, but difficult to do any better. 

3/ Mooving X and Y through the menus is fine, but still the same, I mooves about 1/4 of the same command on X, and J mooves about 1/16 of the same X command. 
2/ Eeprom index error message, but we will fix that later on.

4/ Still Eeprom message.

**Comment by DerAndere1** [comment]
This is already much batter than the non-moving IJK that I had a week ago :)
For the next week my plan is to 
- test in hardware myself
- have another close look at the planner and the feedrate code
- debug using print messages to see at what point the code gives unexpected values. 
- The Sloeber plugin for Eclipse allows debugging using GDB. Maybe that works for debugging Marlin too. Unfortunatelly I only used that approach once so I have not much experience. I documented it here: https://it-by-derandere.blogspot.com/p/blog-page_46.html (section 2.3)

**Comment by hobiseven** [comment]
Regarding debugging you can actually do it directly in vscode. That works fine at least with stm cpus using stlink probes ( 3 euros) and that allows you a few hw breakpoints . Not sure for avr, as I think this is what you use. 
The only constrain is of course to not assign swd/sck pins to any functional io. This is the purpose of the jtag and debug #define at the beginning of the pins_longer3d.h . We can watch variables to some extent and avoid much of the « prints serial » things which is what arduino tool forces you to do.
Maybe avr will be as nice in vscode/ platformio. 

Regarding feedrates, we need to keep a flexible approach as it really depends what the additional axes are used for. For the 2+2 axis foam cutter feedrates applies to x,y . Another rule could be max((x,y),(I,j)). Reason : at a given température the cut speed cannot exceed the feedrate as otherwise the the Hotwire will touch the foam and destroy the part( cnc foam cutting : wire radiates and cut the foam without touching it. ). Going slower than the feedrate in one plane will give a larger radiation cut > the effective wire diameter is larger. 
All that is specific to the machine and it’s use. 

What gets tricky is a situation where x y z do not moove but I j k do moove hence my proposal for the max rule of the 2 Cartesian sets xyz / ijk... homing one of the secondary axis is a typical example .

**Comment by DerAndere1** [comment]
What host software do you use as Gcode sender for 4 axes? I made a configuration for our code and was able to flash. Still no movement of the I stepper, seems to be a config issue. I will try Gabriels branch tomorrow.

**Comment by hobiseven** [comment]
I use the serial port so far, and I send one line of Gcode through the console. 
You can either use a SD card, and play the Gcode directly from Marlin, or for the printer using that board, I also use Octoprint, running on a Pi Zero ( NEVER unplug without shuting down the OS... ) 

You can do both. Even Octoprint with the serial console can do it.

**Comment by DerAndere1** [comment]
Closing as the initial issue seems to be fixed, lets continue to work on the dev_2_rebased branch.
