### ISSUE TITLE
Is U30 Pro supported?

### ISSUE THREAD

**Issue by mrv96** [hobiseven/Marlin2.0.4.4_6axis_Longer3D#2]
Hi, is U30 Pro supported either by this repo or tpruvot fork?

**Comment by hobiseven** [comment]
Hi, this is mainly a Marlin2 repo here , so anything which is supposed to be compatible with Marlin 2 should be OK.
Now, I think U30 Pro board uses an AVR CPU with TMC divers, so it could be, but this will need adaptations. You should ask Longer to provide you the specific Marlin code source they have, and plug in the modification that are already available for Marlin 1.1.9 from the below repo

https://github.com/GabrielBeraldo/Marlin/tree/bf2_6axis_dev

Note that we talk about 6 real axes, not 3 axis + 3 extruders, which is defacto supported by Marlin

**Comment by mrv96** [comment]
Ok. Thank you very much!
